#use "start_oml.ml"
#use "float_format.ml"
#use "fat_tail_data.ml"
#use "summary_data.ml"
#use "skewness_example.ml"
#use "inference_example.ml"
#use "regression_example.ml"
#use "classify_example.ml"
